version: '2'
services:
  calificaciones-api:
    container_name: calificaciones-api
    restart: always
    image: ualmtorres/phalcon-apache-ubuntu
    ports:
      - "8080:80"
    volumes:
      - ./api:/var/www/html

  calificaciones-front: 
    container_name: calificaciones-frontend
    restart: always
    image: php:7.2-apache 
    ports:
      - "8088:80" 
    volumes:
      - ./frontend:/var/www/html 

