name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: composer install

    - name: Build and deploy
      uses: vercel/github-action@v2
      with:
        token: ${{ secrets.VERCEL_TOKEN }}
        project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        version: ${{ github.run_id }}