name: Deploy to Vercel

on:
  push:
    branches:
      - master

jobs:
  phalcon:
    name: Phalcon (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Docs: https://github.com/shivammathur/setup-php
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        extensions: mbstring, dom, zip, phalcon4, pgsql
        coverage: xdebug

    - name: Install dependencies
      run: composer install

    - name: Build and deploy
      uses: vercel/github-action@v2
      with:
        token: ${{ secrets.VERCEL_TOKEN }}
        project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        version: ${{ github.run_id }}